# Generated by Django 4.2.17 on 2025-05-10 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('booking', '0003_coach_alter_event_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_venue', to='company.venue'),
            preserve_default=False,
        ),
    ]
