# Generated by Django 4.2.17 on 2025-05-10 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_company_venues_venue_company'),
        ('booking', '0004_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_coach', to='company.company'),
            preserve_default=False,
        ),
    ]
