# Generated by Django 4.2.17 on 2025-05-13 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_coach'),
        ('booking', '0005_coach_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_on_booking', to='company.coach'),
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
    ]
