# Generated by Django 4.2.17 on 2025-06-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_event_coach_delete_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('day', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['day'],
            },
        ),
    ]
