# Generated by Django 4.2.17 on 2025-06-17 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_refundrequest'),
        ('booking', '0007_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='TemplateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_events', to='company.coach')),
                ('day_of_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.day')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_venue', to='company.venue')),
            ],
        ),
        migrations.CreateModel(
            name='ExcludedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.coach')),
            ],
        ),
    ]
