# Generated by Django 4.2.17 on 2025-06-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_day_options_templateevent_excludeddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='coach_no_show',
            field=models.BooleanField(default=False),
        ),
    ]
