# Generated by Django 4.2.17 on 2025-01-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_alter_score_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
