# Generated by Django 4.2.17 on 2025-05-10 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='venues',
        ),
        migrations.AddField(
            model_name='venue',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='company.company'),
            preserve_default=False,
        ),
    ]
