# Generated by Django 4.2.17 on 2025-05-11 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_company_venues_venue_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='coaches',
        ),
    ]
