# Generated by Django 4.2.17 on 2025-05-11 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0003_remove_company_coaches'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_manager', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
