# Generated by Django 4.2.17 on 2025-06-05 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_event_coach_delete_coach'),
        ('company', '0008_userprofile_token_count_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_token', to='booking.booking'),
        ),
    ]
