# Generated by Django 4.2.17 on 2025-06-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_token_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
    ]
