# Generated by Django 4.2.17 on 2025-06-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_refundrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='auto_updates',
            field=models.BooleanField(default=False),
        ),
    ]
