# Generated by Django 4.2.17 on 2025-07-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='Name', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
