# Generated by Django 4.2.17 on 2025-07-01 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_image_name'),
    ]

    operations = [
    ]
