# Generated by Django 4.2.17 on 2025-07-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_company_token_price_tokenpurchase_token_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='Stripe Connect Account ID for this company.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
