# Generated by Django 4.2.17 on 2025-07-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_company_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID associated with this company.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe Subscription ID for the active subscription.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_end_date',
            field=models.DateField(blank=True, help_text='Date when the current subscription period ends.', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_plan_name',
            field=models.CharField(blank=True, help_text="Name of the subscription plan (e.g., 'Monthly Flat Fee').", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_start_date',
            field=models.DateField(blank=True, help_text='Date when the current subscription period started.', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_status',
            field=models.CharField(blank=True, help_text="Current status of the Stripe subscription (e.g., 'active', 'past_due').", max_length=50, null=True),
        ),
    ]
