from . import views
from django.urls import path

urlpatterns = [
    path('company_dashboard/', views.company_dashboard, name='company_dashboard'),
    path('change_details/', views.change_company_details, name='change_company_details'),
    path('view_coaches/', views.view_coaches, name='view_coaches'),
    path('add_coach/', views.add_coach, name='add_coach'),
    path('remove_coach/', views.remove_coach, name='remove_coach'),
    path('remove_client/<int:client_id>/', views.remove_client, name="remove_client"),
    path('view_bookings/', views.view_bookings, name='view_bookings'),
    path('delete_booking/<int:booking>', views.delete_booking, name='delete_booking'),
    path('view_clients/', views.view_clients, name='view_clients'),
    path('client_details/<int:client_id>/', views.client_details, name='client_details'),
    path('manage_venues', views.manage_venues, name='manage_venues'),
    path('add_venue/', views.add_venue, name='add_venue'),
    path('view_venue/<int:venue_id>/', views.view_venue, name='view_venue'),
    path('edit_venue/<int:venue_id>/', views.edit_venue, name='edit_venue'),
    path('remove_venue/<int:venue_id>/', views.remove_venue, name='remove_venue'),
    path('purchase_tokens', views.purchase_tokens, name='purchase_tokens'),
    path('refund_token/<int:token_id>/', views.refund_token, name='refund_token'),
    path('refund_client_token/<int:token_id>/', views.refund_client_token, name='refund_client_token'),
    path('view_tokens/', views.view_tokens, name='view_tokens'),
    path('view_client_tokens/<int:client_id>/', views.view_client_tokens, name='view_client_tokens'),
    path('view_refund_requests', views.view_refund_requests, name="view_refund_requests"),
    path('approve_refund_request/<int:request_id>/', views.approve_refund_request, name='approve_refund_request'),
    path('deny_refund_request/<int:request_id>/', views.deny_refund_request, name='deny_refund_request'),
    path('client_leave_company/', views.client_leave_company, name='client_leave_company'),
    path('join_company/', views.join_company, name='join_company'),
]